<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use App\Models\Category;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $mobil = Category::where('slug', 'mobil')->first();
        $motor = Category::where('slug', 'motor')->first();
        $hp = Category::where('slug', 'sewa-hp')->first();
        $kamera = Category::where('slug', 'sewa-kamera')->first();

        $vehicles = [
            // Mobil
            [
                'category_id' => $mobil->id,
                'name' => 'Toyota Avanza 1.5 G CVT',
                'slug' => 'toyota-avanza-15-g-cvt',
                'brand' => 'Toyota',
                'model' => 'Avanza',
                'year' => 2023,
                'plate_number' => 'B 1234 ABC',
                'color' => 'Silver',
                'capacity' => 7,
                'transmission' => 'automatic',
                'fuel_type' => 'Bensin',
                'daily_rate' => 350000,
                'weekly_rate' => 2200000,
                'monthly_rate' => 8000000,
                'description' => 'Toyota Avanza terbaru dengan kabin luas, cocok untuk keluarga. Dilengkapi AC dingin dan audio system.',
                'images' => json_encode(['/images/vehicles/avanza-1.jpg', '/images/vehicles/avanza-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $mobil->id,
                'name' => 'Honda Jazz RS CVT',
                'slug' => 'honda-jazz-rs-cvt',
                'brand' => 'Honda',
                'model' => 'Jazz',
                'year' => 2022,
                'plate_number' => 'B 5678 DEF',
                'color' => 'Red',
                'capacity' => 5,
                'transmission' => 'automatic',
                'fuel_type' => 'Bensin',
                'daily_rate' => 400000,
                'weekly_rate' => 2500000,
                'monthly_rate' => 9000000,
                'description' => 'Honda Jazz RS dengan desain sporty, mesin bertenaga, cocok untuk anak muda.',
                'images' => json_encode(['/images/vehicles/jazz-1.jpg', '/images/vehicles/jazz-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $mobil->id,
                'name' => 'Toyota Innova Reborn 2.4 G',
                'slug' => 'toyota-innova-reborn-24-g',
                'brand' => 'Toyota',
                'model' => 'Innova',
                'year' => 2023,
                'plate_number' => 'B 9012 GHI',
                'color' => 'Black',
                'capacity' => 7,
                'transmission' => 'automatic',
                'fuel_type' => 'Diesel',
                'daily_rate' => 550000,
                'weekly_rate' => 3500000,
                'monthly_rate' => 13000000,
                'description' => 'Toyota Innova Reborn kabin luas dan nyaman, mesin diesel irit, cocok untuk perjalanan jauh.',
                'images' => json_encode(['/images/vehicles/innova-1.jpg', '/images/vehicles/innova-2.jpg']),
                'status' => 'rented',
                'owner_id' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $mobil->id,
                'name' => 'Daihatsu Xenia 1.3 R MT',
                'slug' => 'daihatsu-xenia-13-r-mt',
                'brand' => 'Daihatsu',
                'model' => 'Xenia',
                'year' => 2022,
                'plate_number' => 'B 3456 JKL',
                'color' => 'White',
                'capacity' => 7,
                'transmission' => 'manual',
                'fuel_type' => 'Bensin',
                'daily_rate' => 300000,
                'weekly_rate' => 1800000,
                'monthly_rate' => 7000000,
                'description' => 'Daihatsu Xenia handal dan irit bahan bakar, transmisi manual untuk sensasi berkendara maksimal.',
                'images' => json_encode(['/images/vehicles/xenia-1.jpg', '/images/vehicles/xenia-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],

            // Motor
            [
                'category_id' => $motor->id,
                'name' => 'Honda Beat Street',
                'slug' => 'honda-beat-street',
                'brand' => 'Honda',
                'model' => 'Beat',
                'year' => 2023,
                'plate_number' => 'D 1111 AAA',
                'color' => 'Black',
                'capacity' => 2,
                'transmission' => 'automatic',
                'fuel_type' => 'Bensin',
                'daily_rate' => 75000,
                'weekly_rate' => 450000,
                'monthly_rate' => 1500000,
                'description' => 'Honda Beat irit dan gesit, cocok untuk harian dan menjelajah kota.',
                'images' => json_encode(['/images/vehicles/beat-1.jpg', '/images/vehicles/beat-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $motor->id,
                'name' => 'Honda Vario 125 CBS',
                'slug' => 'honda-vario-125-cbs',
                'brand' => 'Honda',
                'model' => 'Vario',
                'year' => 2023,
                'plate_number' => 'D 2222 BBB',
                'color' => 'Blue',
                'capacity' => 2,
                'transmission' => 'automatic',
                'fuel_type' => 'Bensin',
                'daily_rate' => 85000,
                'weekly_rate' => 520000,
                'monthly_rate' => 1800000,
                'description' => 'Honda Vario 125 dengan fitur CBS, nyaman dan aman untuk berkendara.',
                'images' => json_encode(['/images/vehicles/vario-1.jpg', '/images/vehicles/vario-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $motor->id,
                'name' => 'Yamaha NMAX 155',
                'slug' => 'yamaha-nmax-155',
                'brand' => 'Yamaha',
                'model' => 'NMAX',
                'year' => 2023,
                'plate_number' => 'D 3333 CCC',
                'color' => 'Matte Black',
                'capacity' => 2,
                'transmission' => 'automatic',
                'fuel_type' => 'Bensin',
                'daily_rate' => 120000,
                'weekly_rate' => 750000,
                'monthly_rate' => 2500000,
                'description' => 'Yamaha NMAX 155 skutik premium, suspensi empuk dan fitur lengkap.',
                'images' => json_encode(['/images/vehicles/nmax-1.jpg', '/images/vehicles/nmax-2.jpg']),
                'status' => 'rented',
                'owner_id' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $motor->id,
                'name' => 'Honda PCX 160',
                'slug' => 'honda-pcx-160',
                'brand' => 'Honda',
                'model' => 'PCX',
                'year' => 2024,
                'plate_number' => 'D 4444 DDD',
                'color' => 'White',
                'capacity' => 2,
                'transmission' => 'automatic',
                'fuel_type' => 'Bensin',
                'daily_rate' => 135000,
                'weekly_rate' => 850000,
                'monthly_rate' => 3000000,
                'description' => 'Honda PCX 160 skutik premium kelas atas, kenyamanan dan gaya dalam satu paket.',
                'images' => json_encode(['/images/vehicles/pcx-1.jpg', '/images/vehicles/pcx-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],

            // HP
            [
                'category_id' => $hp->id,
                'name' => 'iPhone 15 Pro 256GB',
                'slug' => 'iphone-15-pro-256gb',
                'brand' => 'Apple',
                'model' => 'iPhone 15 Pro',
                'year' => 2024,
                'plate_number' => 'N/A',
                'color' => 'Titanium Black',
                'capacity' => 1,
                'transmission' => 'automatic',
                'fuel_type' => null,
                'daily_rate' => 150000,
                'weekly_rate' => 900000,
                'monthly_rate' => 3000000,
                'description' => 'iPhone 15 Pro 256GB, chip A17 Pro, kamera 48MP. Cocok untuk kebutuhan profesional.',
                'images' => json_encode(['/images/vehicles/iphone15pro-1.jpg', '/images/vehicles/iphone15pro-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $hp->id,
                'name' => 'Samsung Galaxy S24 Ultra 512GB',
                'slug' => 'samsung-galaxy-s24-ultra-512gb',
                'brand' => 'Samsung',
                'model' => 'Galaxy S24 Ultra',
                'year' => 2024,
                'plate_number' => 'N/A',
                'color' => 'Titanium Gray',
                'capacity' => 1,
                'transmission' => 'automatic',
                'fuel_type' => null,
                'daily_rate' => 175000,
                'weekly_rate' => 1050000,
                'monthly_rate' => 3500000,
                'description' => 'Samsung Galaxy S24 Ultra 512GB, S-Pen, kamera 200MP, AI features.',
                'images' => json_encode(['/images/vehicles/s24ultra-1.jpg', '/images/vehicles/s24ultra-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $hp->id,
                'name' => 'iPhone 14 128GB',
                'slug' => 'iphone-14-128gb',
                'brand' => 'Apple',
                'model' => 'iPhone 14',
                'year' => 2022,
                'plate_number' => 'N/A',
                'color' => 'Midnight',
                'capacity' => 1,
                'transmission' => 'automatic',
                'fuel_type' => null,
                'daily_rate' => 100000,
                'weekly_rate' => 600000,
                'monthly_rate' => 2000000,
                'description' => 'iPhone 14 128GB, performa handal untuk kebutuhan sehari-hari.',
                'images' => json_encode(['/images/vehicles/iphone14-1.jpg', '/images/vehicles/iphone14-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],

            // Kamera
            [
                'category_id' => $kamera->id,
                'name' => 'Canon EOS R6 Mark II Body Only',
                'slug' => 'canon-eos-r6-mark-ii',
                'brand' => 'Canon',
                'model' => 'EOS R6 Mark II',
                'year' => 2023,
                'plate_number' => 'N/A',
                'color' => 'Black',
                'capacity' => 1,
                'transmission' => 'automatic',
                'fuel_type' => null,
                'daily_rate' => 350000,
                'weekly_rate' => 2100000,
                'monthly_rate' => 7000000,
                'description' => 'Canon EOS R6 Mark II, kamera mirrorless full-frame 24.2MP, burst 40fps, video 4K 60fps.',
                'images' => json_encode(['/images/vehicles/canoneosr6-1.jpg', '/images/vehicles/canoneosr6-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $kamera->id,
                'name' => 'Sony A7 III Body Only',
                'slug' => 'sony-a7-iii',
                'brand' => 'Sony',
                'model' => 'A7 III',
                'year' => 2021,
                'plate_number' => 'N/A',
                'color' => 'Black',
                'capacity' => 1,
                'transmission' => 'automatic',
                'fuel_type' => null,
                'daily_rate' => 300000,
                'weekly_rate' => 1800000,
                'monthly_rate' => 6000000,
                'description' => 'Sony A7 III, mirrorless full-frame 24.2MP, autofocus hybrid, video 4K HDR.',
                'images' => json_encode(['/images/vehicles/sonya7iii-1.jpg', '/images/vehicles/sonya7iii-2.jpg']),
                'status' => 'available',
                'owner_id' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => $kamera->id,
                'name' => 'GoPro Hero 12 Black',
                'slug' => 'gopro-hero-12-black',
                'brand' => 'GoPro',
                'model' => 'Hero 12 Black',
                'year' => 2023,
                'plate_number' => 'N/A',
                'color' => 'Black',
                'capacity' => 1,
                'transmission' => 'automatic',
                'fuel_type' => null,
                'daily_rate' => 125000,
                'weekly_rate' => 750000,
                'monthly_rate' => 2500000,
                'description' => 'GoPro Hero 12 Black, action camera waterproof 5.3K, stabilisasi HyperSmooth 6.0.',
                'images' => json_encode(['/images/vehicles/gopro12-1.jpg', '/images/vehicles/gopro12-2.jpg']),
                'status' => 'maintenance',
                'owner_id' => 2,
                'is_active' => true,
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::create($vehicle);
        }
    }
}
